Sources/Applications/ApplicationsLogicController.swift

Refactors how applications are re-launched.
Instead of relying on `Shell` to execute commands, `NSAppleScript` is now used in order to quit applications and `NSWorkspace` is used to launch the application after the new setting has been applied.
Fixes #1

Refactor logic controller to use NSAppleScript and NSWorkspace

---

Gray.xcodeproj/project.pbxproj
Resources/Base.lproj/MainMenu.xib
Sources/AppDelegate.swift
Sources/VersionController.swift

This PR implements version updates using GitHub as the source of truth.
It fetches `.current-version` from the `master`-branch and checks that number towards the application bundle identifier. If a new version is found, the app will show an update dialog.
If no new version is found, the user will be presented with this kind of message:
Checking for new updates is also available via the menu bar, like you would expect:

Implement version checking towards GitHub

---

Resources/Info.plist
Sources/Shell.swift

To avoid recursion, the `queue` is now created on the `Shell` class instead of inside the `launch` function.

Create queue on Shell instead of inside launch command

---

Sources/Applications/ApplicationsLogicController.swift

Change the order by how plist locations are prioritized. Containers are now used as the new default and `~/Library/Preferences` is the fallback. This fixes issues with apps like Mail.
Fixes https://github.com/zenangst/Gray/issues/7

Fix bug with Mail not changing appearance.

---

Resources/Info.plist
Sources/Applications/Logic/ApplicationsLogicController.swift

Electron apps are now excluded from the list of applications that can change appearance.
Fixes https://github.com/zenangst/Gray/issues/18

Exclude Electron apps

---

Sources/Applications/Views/ApplicationGridView.swift

Accent color will now be used to show more clearly which apps have a selected appearance and which still follow the system.

Use .controlAccentColor for applications with a selected appearance

---

Sources/Main/MainViewController.swift

This PR improves clicking on an application while searching. Before it would forget that it had a query, now it will remember the current query but perform the appropriate updates on the collection of applications.

Keep search query after switching appearance for application

---

Sources/AppDelegate.swift

- Window on AppDelegate is now weak so that it gets deallocated when you close it.
- If the window is closed and the application is reactivate, a new window is created.

Improve re-opening window

---

Gray.xcodeproj/project.pbxproj
Sources/Features/Applications/Logic/ApplicationsLogicController.swift

This PR removes VMWare from the list of applications that you can change the appearance of.
It has been known to cause issues for people so it would be good to prevent that entirely until VMWare builds their app and links it against the latest SDK.
It also fixes the build script, now it will only copy the application and not everything else in the build folder.
See #42 for reference

Exclude VMWare

---

Resources/Info.plist
Sources/Features/Applications/Logic/ApplicationsLogicController.swift
Sources/Features/Applications/View Controllers/ApplicationsViewController.swift
Sources/Features/Applications/Views/ApplicationGridView.swift

Enable resetting application by using the second mouse button to open a small menu on the application view.
Resetting an application runs the follwing command:
```fish
/usr/bin/killall -u $USER cfprefsd
defaults delete \(application.bundleIdentifier) NSRequiresAquaSystemAppearance
defaults read \(application.bundleIdentifier) NSRequiresAquaSystemAppearance \(application.preferencesUrl.path)
```

Adds an NSMenu to the ApplicationGridView

---

Resources/Info.plist
Sources/Features/Applications/Logic/ApplicationsLogicController.swift

The application logic controller will now scan the following folders
- Applications
- Applications/Utilities
- Applications/Xcode.app/Contents/Applications
The only app exception in the list is Finder which is added with an absolute path.
First attempt at solving #45

Refactor ApplicationsLogicController to scan additional folders

---

README.md
Resources/Info.plist
Sources/Features/Applications/Logic/ApplicationsLogicController.swift

This intends to fix a bug that the method throws when trying to parse the application folder. If it throws, no applications would be visible in the GUI.

Use try/catch instead of try

---

Sources/Features/Applications/Logic/ApplicationsLogicController.swift

Hope this isn't too much. Please see the in-code notes especially about `/System/Library/CoreServices`. There are lot of non-application bundles in there.
```
~/Applications
~/Developer/Applications
/Network/Applications
/Network/Developer/Applications
---
/System/Library/CoreServices # incl. ./Applications
/Applications/Xcode.app/Contents/Developer/Applications
~/Library/Developer/Xcode/DerivedData
/Users/Shared/Applications
```
Note: I'm not sure if passing the absolute POSIX path like that is OK in Swift; cf. e.g. `/Developer/Applications`. EDIT: fixed with third commit, but some trailing slashes are missing from paths output.

Add several macOS (non-) default application locs

---

Sources/Features/Applications/Logic/ApplicationsLogicController.swift

Only look for subfolders in paths that contain "/Applications"

Improve performance of recursive lookup

---

Podfile
Podfile.lock
Resources/Info.plist
Sources/Application/AppDelegate.swift
Sources/Features/Applications/Logic/ApplicationsLogicController.swift

Some applications don't have a bundle name in their property list, that would mean that they don't show up in the list of applications. To work around this issue, the executable name will be used as bundle name if it is not declared in the property list.
Fixes #60

Fix application without bundle name not showing up

---

Gray.xcodeproj/project.pbxproj
Podfile.lock
Sources/Application/AppDelegate.swift
Sources/Application/LayoutFactory.swift
Sources/Features/Applications/Logic/ApplicationsLogicController.swift
Sources/Features/Applications/View Controllers/ApplicationsLoadingViewController.swift
Sources/Features/Applications/View Controllers/ApplicationsViewController.swift
Sources/Features/Applications/Views/ApplicationGridView.swift
Sources/Features/Main/MainContainerViewController.swift
Sources/Shared/LabelViewController.swift

- The window can now be resized with `resizeIncrements` on `NSWindow`
- Updates to a new version of `Family` (0.11.3) 
- Implements a loading screen that is displayed when `Gray` is parsing applications (you probably won't see this screen, see screenshot).
- Minor GUI tweaks to layout sizes.

Implement loading screen for parsing applications

---

Sources/Features/Applications/Views/ApplicationGridView.swift
Sources/Features/SystemPreferences/Views/SystemPreferenceView.swift
Sources/Utilities/IconController.swift

- Improves performance by reducing the size of the icons used in the application, the processed icon is then saved to disk and reused across application launches.
- Improves scrolling performance because there is less heavy lifting when processing images.
- Adds missing border on application cell.

Feature image caching

---

Sources/Application/AppDelegate.swift

By removing this line, the application will remember the last size that the user had. It makes sense to not reset the size now that the window accepts resizing.

Remove setting the frame

---

Sources/Features/Applications/View Controllers/ApplicationsFeatureViewController.swift

This improves searching by lowercasing both the targets and the query.

Lowercase search query for better results

---

Gray.xcodeproj/project.pbxproj
Localisations/LocalizedUtils.swift
Localisations/en.lproj/Localizable.strings
Localisations/zh-Hans.lproj/Localizable.strings
Podfile.lock
Resources/Assets.xcassets/Colors/Dark.colorset/Contents.json
Resources/Assets.xcassets/Colors/Light.colorset/Contents.json
Resources/en.lproj/MainMenu.strings
Resources/zh-Hans.lproj/MainMenu.xib
Sources/Alerts/AlertsController.swift
Sources/Application/Toolbar/SearchToolbarItem.swift
Sources/Features/Applications/AppearanceAware.swift
Sources/Features/Applications/ApplicationGridView.swift
Sources/Features/Applications/ApplicationListView.swift
Sources/Features/Applications/ApplicationsFeatureViewController.swift
Sources/Features/Applications/ApplicationsLogicController.swift
Sources/Features/Main/MainContainerViewController.swift
Sources/Features/SystemPreferences/SystemLogicController.swift
Sources/Features/SystemPreferences/SystemPreferenceFeatureViewController.swift
Sources/Features/SystemPreferences/SystemPreferenceView.swift

1. add Simplified Localization
2. add 
```swift
extension String {
var localized: String {
return NSLocalizedString(self, comment: self)
}
}
```
now it is easy to localize the Gray
3. it is working nice ！

add Simplified Chinese Localization

---

.travis.yml
Gemfile
Gray.xcodeproj/project.pbxproj
Podfile
Podfile.lock
Resources/Base.lproj/MainMenu.xib
Sources/Features/Applications/Application.swift
Sources/Features/Applications/ApplicationGridView.swift
Sources/Features/Applications/ApplicationListView.swift
Sources/Features/Applications/ApplicationsFeatureViewController.swift
Sources/Features/Applications/ApplicationsLogicController.swift
Voodoo/Output/CollectionViewItemComponent-macOS.generated.swift

The application logic controller will now try and resolve a localized name
for the application rather than using the executable name.

Add initial support for localized app names
