Gray.xcodeproj/project.pbxproj, Resources/Info.plist, Sources/Applications/ApplicationCollectionViewController.swift, Sources/Applications/ApplicationListView.swift, Sources/Applications/ApplicationsDataSource.swift, Sources/IconController.swift
This PR implements the loading of icons.
=> Implement IconController and add icon to application view

Gray.xcodeproj/project.pbxproj, Podfile.lock, Sources/Applications/ApplicationCollectionViewController.swift, Sources/Applications/ApplicationGridView.swift, Sources/Applications/ApplicationListView.swift, Sources/Applications/ApplicationsDataSource.swift, Sources/Applications/ApplicationsViewController.swift
This PR implements the grid view and will now act as the new default until we add a toggle between grid and list view.
=> Implement grid view

Resources/Info.plist, Sources/Applications/ApplicationsLogicController.swift
This PR adds Finder to the list of applications that can be configured.
=> Add Finder to list of applications

Resources/Info.plist, Sources/AppDelegate.swift, Sources/Applications/Logic/ApplicationsLogicController.swift, Sources/Applications/Models/Application.swift, Sources/Applications/Views/ApplicationGridView.swift, Sources/Utilities/Shell.swift
- Minor improvements to the application window
- The window now uses a fixed size
- Improves changing appearance for apps like Contacts and Mail by killing the `cfprefsd` process
- Uses `PlistBuddy` to write the new attribute to the resolved property list
- Internal improvements to shell scripting
- Apps that don't have a specific preference are now displayed as `System appearance`
=> Various improvements

README.md
Noticed a small typo in the readme and couldn't help but fix it. Reworked a sentence in the intro too, because it sounded a bit off. Hope you don't mind (too much).
=> Just some text fixes for the readme

Resources/Info.plist, Sources/Applications/Logic/ApplicationsLogicController.swift
This PR improves how applications are being re-launched. Now when you decide to change the appearance of a running application, that application will no longer steal focus when it re-launches.
Fixes https://github.com/zenangst/Gray/issues/12
=> Improve re-launching applications

Sources/Applications/Logic/ApplicationsLogicController.swift
Instead of using Apple scripting to close the application, NSRunningApplication will be used to quit the application.
This PR tries to solve #26 #7
=> Refactor ApplicationsLogicController.toggleAppearance

Gray.xcodeproj/project.pbxproj, README.md, Resources/Info.plist, Sources/Applications/Logic/ApplicationsLogicController.swift
- New settings now use `true` and `false` instead of `YES` and `NO`
- Adds `NSLog` statements for better debugging of #7
=> Refactor application toggle

Gray.xcodeproj/project.pbxproj, Podfile.lock, Resources/Info.plist, Sources/AppDelegate.swift, Sources/Main/MainViewController.swift, Sources/Toolbar/SearchField.swift, Sources/Toolbar/SearchToolbarItem.swift, Sources/Toolbar/Toolbar.swift
This PR adds the initial implementation of the search feature.
It looks like this:
=> Add initial implementation of search

Gray.xcodeproj/project.pbxproj, Podfile.lock, Resources/Assets.xcassets/Colors/Contents.json, Resources/Assets.xcassets/Colors/Dark.colorset/Contents.json, Resources/Assets.xcassets/Colors/Light.colorset/Contents.json, Resources/Info.plist, Sources/AppDelegate.swift, Sources/Applications/Data Sources/ApplicationsDataSource.swift, Sources/Applications/View Controllers/ApplicationsCollectionViewController.swift, Sources/Applications/Views/ApplicationGridView.swift, Sources/LayoutFactory.swift, Sources/Main/MainViewController.swift, Sources/Shared/LabelViewController.swift, Sources/SystemPreferences/Data Sources/SystemPreferenceDataSource.swift, Sources/SystemPreferences/View Controllers/SystemPreferenceCollectionViewController.swift, Sources/SystemPreferences/Views/SystemPreferenceView.swift
- Adds title labels to the sections
- Adds LayoutFactory to create grid layouts
- Visual changes to the collection view items
- Uses a new version of the Family framework (0.6.4)
- Changes the window size
=> UI improvements and improved search

Resources/Info.plist, Sources/Applications/Data Sources/ApplicationsDataSource.swift, Sources/Applications/Logic/ApplicationsLogicController.swift, Sources/Applications/Models/Application.swift, Sources/Applications/View Controllers/ApplicationsCollectionViewController.swift, Sources/Applications/Views/ApplicationGridView.swift, Sources/SystemPreferences/Logic/SystemLogicController.swift
- Checks if SIP is enabled
- Queries the plist to check readability
- Adds `restricted` to Application
- Adds flow for opening system preferences and giving Gray Full Disk Access
=> Implement handling of restricted applications

Gray.xcodeproj/project.pbxproj, Sources/Application/AppDelegate.swift, Sources/Application/DepedencyContainer.swift, Sources/Features/Applications/Data Sources/ApplicationsDataSource.swift, Sources/Features/Applications/View Controllers/ApplicationsViewController.swift, Sources/Features/Main/MainContainerViewController.swift, Sources/Features/SystemPreferences/Data Sources/SystemPreferenceDataSource.swift, Sources/Features/SystemPreferences/View Controllers/SystemPreferenceViewController.swift, Sources/Utilities/IconController.swift
Improves how icons are loaded by doing the heavy lifting in a different queue.
=> Improve icon loading

Sources/Features/Applications/Logic/ApplicationsLogicController.swift
Improves the overall performance when invoking commands as all calls are now dispatched into a user-initiated queue.
=> Make DispatchQueue .userInitiated

Podfile.lock, Sources/Application/AppDelegate.swift, Sources/Features/Applications/Logic/ApplicationsLogicController.swift, Sources/Features/Applications/View Controllers/ApplicationsViewController.swift
This PR aims to improve performance even further.
Now the application's parsing is done in a background thread which frees up the main thread.
There is a small delay before the application restarts if it is already open.
Updates some of the frameworks which fixes some rendering issues.
=> Improve performance part deux

Resources/Info.plist, Sources/Shared/LabelViewController.swift
Refactor label view controller to do set up in viewDidLoad.
Bumps the version number.
=> Improve performance

Sources/Features/Applications/Logic/ApplicationsLogicController.swift
Fixes https://github.com/zenangst/Gray/issues/68
=> Remove excluding Electron apps

Sources/Application/Toolbar/SearchField.swift, Sources/Application/Toolbar/SearchToolbarItem.swift, Sources/Application/Toolbar/Toolbar.swift
=> Use NSSearchFieldCell instead of NSTextField

Sources/Features/Applications/Models/Application.swift, Sources/Features/Applications/View Controllers/ApplicationsViewController.swift
Refactor search feature to use NSPredicate to get more accurate results.
=> Improve searching with NSPredicate

Sources/Features/Main/MainContainerViewController.swift
This restores functionality that was removed in the previous PR.
The header for the application feature will now be updated with the search query, just like before.
=> Improve collection view header

Sources/Features/Applications/ApplicationsLogicController.swift
=> Use executableName instead of bundleName for uniqueness

Podfile.lock
```diff
- Blueprints (0.9.0)
- Differific (0.5.2)
- Family (0.13.6)
+ Blueprints (0.10.1)
+ Differific (0.6.0)
+ Family (0.14.3)
```
=> Updates to new version of frameworks

Gray.xcodeproj/project.pbxproj, Resources/Base.lproj/MainMenu.xib, Sources/Application/AppDelegate.swift, Sources/Features/Export/ExportController.swift
This PR implements support for exporting all settings of Gray into a text file.
=> Implement basic export feature

Gray.xcodeproj/project.pbxproj, Resources/Base.lproj/MainMenu.xib, Sources/Application/AppDelegate.swift, Sources/Features/Applications/ApplicationsLoadingViewController.swift, Sources/Features/Import/ImportController.swift, Sources/Features/Main/MainContainerViewController.swift
This PR adds functionality for importing settings.
It is a follow PR for the import/export feature that started with this PR #91
=> Feature importing settings

Resources/Base.lproj/MainMenu.xib
Basically just fixes a broken/misdirected keybinding for searching.
=> Fix faulty keyboard shortcut binding for search

Podfile.lock, Resources/Base.lproj/MainMenu.xib, Resources/Info.plist
- 🐞 Fix faulty keyboard shortcut bindings
- 🍱 Update frameworks
=> Fix bindings and update frameworks

Gray.xcodeproj/project.pbxproj, Podfile.lock, Resources/Info.plist, Sources/Application/AppDelegate.swift, Sources/Features/Applications/ApplicationsFeatureViewController.swift, Sources/Features/Applications/ApplicationsLoadingViewController.swift, Sources/Features/Applications/ApplicationsLogicController.swift, Voodoo/Output/CollectionViewItemComponent-macOS.generated.swift, Voodoo/Output/StatefulItem-macOS.generated.swift, Voodoo/Output/ViewControllerFactory-macOS.generated.swift, Voodoo/Templates/CollectionViewItemComponent-macOS.stencil
- Fix minor UI glitches
- Fix UI related constraint issues
- Allow the window to be larger
- Update to new versions of the third-party frameworks
- Fix issue with code generation
=> Bug fixes and improvements

.travis.yml, Gray.xcodeproj/project.pbxproj, Podfile.lock, Resources/Info.plist, Sources/Features/Applications/ApplicationGridView.swift, Sources/Features/Applications/ApplicationListView.swift, Sources/Features/Main/MainContainerViewController.swift, Sources/Features/Views/OpaqueView.swift, Voodoo/Output/CollectionViewItemComponent-macOS.generated.swift, Voodoo/Output/StatefulItem-macOS.generated.swift, Voodoo/Output/ViewControllerFactory-macOS.generated.swift
- Introduce `OpaqueView`
- Use new `Family` syntax for building view controller compositions
- Update to latest and greatest version of `Family`
- Use newer version of `Sourcery`
=> Update use of frameworks and other optimizations

Gray.xcodeproj/project.pbxproj, Podfile.lock, Sources/Features/Applications/ApplicationsLogicController.swift
- 🚸 Updates to the latest version of underlying UI framework `Family`
- 🌅 Adds new path to include new core applications on macOS Catalina
- 🦅 Use Swift 5
=> Add additional apps on macOS Catalina

README.md
Changed the linked version from 0.14.0 to 0.15.0.
=> Update download link in README.md

Localisations/ja.lproj/Localizable.strings
I translated into japanese lang.
=> Translation >ja
